server {
    listen 80; #포트 80

    location /{
        #접속시 flask-app 이라는 이름의 5000번 포트로 토스

        proxy_pass http://flask-app:5000;

        #(선택) 접속자의 실제 ip 주소 같은 정보를 flask-app 으로 넘긴다
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

    }
}

