server {
    listen 80;
    server_name awsstudy.duckdns.org;

    # 80번(HTTP)으로 들어오면 무조건 HTTPS로 튕겨버리기 (리다이렉트)
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name awsstudy.duckdns.org;

    # 👇 공유받은 인증서 위치 지정
    ssl_certificate /etc/letsencrypt/live/awsstudy.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/awsstudy.duckdns.org/privkey.pem;

    location / {
        proxy_pass http://flask-app:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}